### ISSUE TITLE
Bat social call annotations in figshare

### ISSUE THREAD

**Issue by maRce10** [audioblast/annotations#1]
Hi 

I want to add these two annotations to the data base:

https://ndownloader.figshare.com/files/21528531
https://ndownloader.figshare.com/files/21528522

cheers

**Comment by edwbaker** [comment]
To match the manuscript I think these changes should be made:

1) Make alt a numeric value
2) The current 'target_signal' should be 'type' to match the template
3) I think what is currently in 'type' should be concatenated with 'effort'

What do you think?

**Comment by edwbaker** [comment]
Oh hold on, things have changed in the manuscript from the template. What is currently in 'type' looks like it belongs in BasisOfRecord according to the manuscript that might clash with DarwinCore.

**Comment by maRce10** [comment]
So should I wait til we reach some agreement?

**Comment by edwbaker** [comment]
I think so. 
The manuscript is a bit messy around this topic. I'm going to try and simplify it by adding a table.

**Comment by maRce10** [comment]
Hi 

here are the annotations with the suggested changes:

https://ndownloader.figshare.com/files/21844200
https://ndownloader.figshare.com/files/21844203

**Comment by edwbaker** [comment]
Import is currently running.

**Comment by edwbaker** [comment]
Completed.

**Comment by maRce10** [comment]
thanks!
